import '../globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import TheHeader from "@/app/components/TheHeader";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function HeaderLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className="layout header">
        <TheHeader></TheHeader>
        {children}
      </div>
  )
}
